apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-1
  template:
    metadata:
      labels:
        app: devops-1
    spec:
      containers:
        - name: devops-1-server
          image: ghcr.io/andapattanachoo/devops-1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-1
  labels:
    app: devops-1
spec:
  selector:
    app: devops-1
  ports:
    - name: http
      protocol: TCP
      port: 9999
      targetPort: 80
  type: ClusterIP